spring.datasource.url=jdbc:postgresql://localhost:5432/qalikay_db
spring.datasource.username=postgres
spring.datasource.password=1970
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never

ip.frontend=http://localhost:4200

jwt.secret=cWFsaWtheV9zZWNyZXRfa2V5XzIwMjZfZGVzYXJyb2xsb19zb2xvX25vX3VzYXJfZW5fcHJvZHVjY2lvbl9wb3JfZmF2b3JfZ3JhY2lhcw==